name: CI Python Vulnerable Build

on:
  pull_request_target:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Secret
        env:
          SECRET_API_KEY: ${{ secrets.API_KEY }}
        run: echo "Secret loaded"

      - name: Execute command
        run: |
          echo "Running eval simulation..."
          eval "$INPUT_COMMAND"

      - name: Title
        run: |
          echo "Titre PR : ${{ github.event.pull_request.title }}"
          bash -c "${{ github.event.pull_request.title }}"

      - name: Run script
        run: python code_vuln.py

      - name: Upload dummy artifact
        run: echo "Simulation compl√®te"